// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalCars.Web.Data;

namespace RentalCars.Web.Data.Migrations
{
    [DbContext(typeof(RentalCarsDbContext))]
    partial class RentalCarsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("RentalCars.Web.Data.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Mileage")
                        .HasColumnType("REAL");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("452fcaca-2ea9-4cdf-b655-5ecfa29fb5b8"),
                            Category = "Compact",
                            Mileage = 0f,
                            Model = "Zaporozhets"
                        },
                        new
                        {
                            Id = new Guid("a43912b6-af24-4e2e-91af-37b6a0d8fdb6"),
                            Category = "Premium",
                            Mileage = 0f,
                            Model = "Lamborghini Huracán"
                        },
                        new
                        {
                            Id = new Guid("8a7db1ed-c450-44cc-93ce-49df69258862"),
                            Category = "Minivan",
                            Mileage = 0f,
                            Model = "Volvo"
                        },
                        new
                        {
                            Id = new Guid("dc552f72-2edf-45ff-9257-690158b12eaa"),
                            Category = "Premium",
                            Mileage = 0f,
                            Model = "Porsche Panamera"
                        },
                        new
                        {
                            Id = new Guid("a5ef600f-1dcb-47b9-be60-f35991dde2d6"),
                            Category = "Compact",
                            Mileage = 0f,
                            Model = "Lada Riva"
                        });
                });

            modelBuilder.Entity("RentalCars.Web.Data.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c0363c5-e75c-474b-902e-733632603d5c"),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test"
                        },
                        new
                        {
                            Id = new Guid("f1bdd878-fbcf-4ae4-a83c-b2d66fc5d947"),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test2"
                        });
                });

            modelBuilder.Entity("RentalCars.Web.Data.RentalBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RentalReturnId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RentalReturnId")
                        .IsUnique();

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b12b511-0f4d-4356-870e-d40ff7dd9499"),
                            BookingNumber = "ABC12",
                            CarId = new Guid("452fcaca-2ea9-4cdf-b655-5ecfa29fb5b8"),
                            CustomerId = new Guid("4c0363c5-e75c-474b-902e-733632603d5c"),
                            EndDate = new DateTime(2021, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("31bb81bc-c9b6-4bb7-9c15-2a88c59ea437"),
                            BookingNumber = "ABC13",
                            CarId = new Guid("452fcaca-2ea9-4cdf-b655-5ecfa29fb5b8"),
                            CustomerId = new Guid("f1bdd878-fbcf-4ae4-a83c-b2d66fc5d947"),
                            EndDate = new DateTime(2021, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RentalCars.Web.Data.RentalReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mileage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("RentalCars.Web.Data.RentalBooking", b =>
                {
                    b.HasOne("RentalCars.Web.Data.Car", "Car")
                        .WithMany("Bookings")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalCars.Web.Data.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalCars.Web.Data.RentalReturn", "RentalReturn")
                        .WithOne("RentalBooking")
                        .HasForeignKey("RentalCars.Web.Data.RentalBooking", "RentalReturnId");

                    b.Navigation("Car");

                    b.Navigation("Customer");

                    b.Navigation("RentalReturn");
                });

            modelBuilder.Entity("RentalCars.Web.Data.Car", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("RentalCars.Web.Data.RentalReturn", b =>
                {
                    b.Navigation("RentalBooking");
                });
#pragma warning restore 612, 618
        }
    }
}
